/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntellectualPropertyRouteImport } from './routes/intellectual-property'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWorkspaceSettingsRouteImport } from './routes/admin.workspace-settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPromptTemplatesRouteImport } from './routes/admin.prompt-templates'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminDocTemplatesRouteImport } from './routes/admin.doc-templates'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntellectualPropertyRoute = IntellectualPropertyRouteImport.update({
  id: '/intellectual-property',
  path: '/intellectual-property',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspaceSettingsRoute = AdminWorkspaceSettingsRouteImport.update({
  id: '/workspace-settings',
  path: '/workspace-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromptTemplatesRoute = AdminPromptTemplatesRouteImport.update({
  id: '/prompt-templates',
  path: '/prompt-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocTemplatesRoute = AdminDocTemplatesRouteImport.update({
  id: '/doc-templates',
  path: '/doc-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/doc-templates': typeof AdminDocTemplatesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/prompt-templates': typeof AdminPromptTemplatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspace-settings': typeof AdminWorkspaceSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/doc-templates': typeof AdminDocTemplatesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/prompt-templates': typeof AdminPromptTemplatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspace-settings': typeof AdminWorkspaceSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/doc-templates': typeof AdminDocTemplatesRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/prompt-templates': typeof AdminPromptTemplatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspace-settings': typeof AdminWorkspaceSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cancellation'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/intellectual-property'
    | '/login'
    | '/otp'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/workspace'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/content'
    | '/admin/doc-templates'
    | '/admin/email-templates'
    | '/admin/features'
    | '/admin/knowledge'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/permissions'
    | '/admin/prompt-templates'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/workspace-settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cancellation'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/intellectual-property'
    | '/login'
    | '/otp'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/workspace'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/content'
    | '/admin/doc-templates'
    | '/admin/email-templates'
    | '/admin/features'
    | '/admin/knowledge'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/permissions'
    | '/admin/prompt-templates'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/workspace-settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cancellation'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/intellectual-property'
    | '/login'
    | '/otp'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/workspace'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/content'
    | '/admin/doc-templates'
    | '/admin/email-templates'
    | '/admin/features'
    | '/admin/knowledge'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/permissions'
    | '/admin/prompt-templates'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/subscriptions'
    | '/admin/system'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/workspace-settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntellectualPropertyRoute: typeof IntellectualPropertyRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intellectual-property': {
      id: '/intellectual-property'
      path: '/intellectual-property'
      fullPath: '/intellectual-property'
      preLoaderRoute: typeof IntellectualPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspace-settings': {
      id: '/admin/workspace-settings'
      path: '/workspace-settings'
      fullPath: '/admin/workspace-settings'
      preLoaderRoute: typeof AdminWorkspaceSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prompt-templates': {
      id: '/admin/prompt-templates'
      path: '/prompt-templates'
      fullPath: '/admin/prompt-templates'
      preLoaderRoute: typeof AdminPromptTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doc-templates': {
      id: '/admin/doc-templates'
      path: '/doc-templates'
      fullPath: '/admin/doc-templates'
      preLoaderRoute: typeof AdminDocTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDocTemplatesRoute: typeof AdminDocTemplatesRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPromptTemplatesRoute: typeof AdminPromptTemplatesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkspaceSettingsRoute: typeof AdminWorkspaceSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDocTemplatesRoute: AdminDocTemplatesRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPromptTemplatesRoute: AdminPromptTemplatesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkspaceSettingsRoute: AdminWorkspaceSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntellectualPropertyRoute: IntellectualPropertyRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
